brain_node:
  ros__parameters:
    game:
      team_id: 29 # consistant with GameControl
      player_id: 1 # 0 | 1 | 2 | 3
      field_type: "gdc" # adult_size | kid_size | gdc
      player_role: "striker" # striker | goal_keeper
      player_attack_side: "left"
      player_start_pos: 0.5 # [-1.0, 1.0] -1.0 is left side, 1.0 is right side

    robot:
      robot_height: 1.0
      odom_factor: 1.2
      vx_factor: 1.1
      yaw_offset: 0.0
      joystick: "logitech" # logitech | beitong

    image:
      width: 960
      height: 540

    visual_odom:
      topic: "/camera/camera/pose"

    enable_com: true

    rerunLog:
      enable: true
      server_addr: "rerun+http://127.0.0.1:9876/proxy"